# A sample Gemfile
source "https://rubygems.org"


# gem "rails"
gem 'selenium-webdriver', '~> 2.48.1'
gem 'cucumber', '~> 2.1.0'
gem 'capybara'
gem 'rspec'
gem 'rspec-expectations'
gem 'rspec-core'
gem "chromedriver-helper"

